version: "2"
services:
  db:
    build: db-materials
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
    - 5432
    ports:
    - 5432:5432
    restart: always
  app:
    build: Backend
    expose:
    - 8080
    ports:
    - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
  ui:
    build: react-app
    ports:
      - 3000:3000
    depends_on:
      - app
