services:
  db:
    image: postgres
    volumes:
      - /home/john/srv2/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    restart: always
  app:
    build: .
    ports: 
      - 8080:8080
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
